### ISSUE TITLE
Error no release found

### ISSUE THREAD

**Issue by fusionstrings** [stevemao/github-remove-all-releases#1]
I tried this plugin using gulp as well as using CLI but I am getting following error `Error: No releases found`.

**Comment by stevemao** [comment]
Its quite self-explanatory? If you think there's a bug please provide a lot more details or just PR with failing tests.

**Comment by fusionstrings** [comment]
Sorry @stevemao for not being more clear. Well I do have releases under my git hub repository https://github.com/fusionstrings/project-fusion/releases , so it's odd that tool says no releases found.

**Comment by stevemao** [comment]
I can't see any release now. Also what command did you run? Can you try the pure GitHub API?

**Comment by fusionstrings** [comment]
I am not sure why you are not able to see any release 
![image](https://cloud.githubusercontent.com/assets/450624/9832553/0e5afbdc-599c-11e5-8fa2-00a6c9324086.png)

I ran following gulp task

```
gulp.task('github-remove-all-releases', done => {
  githubRemoveAllReleases({
    type: "oauth",
    token: process.env.CONVENTIONAL_GITHUB_RELEASER_TOKEN // change this to your own GitHub token or use an environment variable
  }, 'fusionstrings', 'project-fusion', done);
});
```

As well following command on global install

```
$ github-remove-all-releases fusionstrings project-fusion -t GIT_TOKEN
Error: No releases found
```

By using direct github api, neither https://api.github.com/repos/fusionstrings/project-fusion/releases nor https://api.github.com/repos/stevemao/github-remove-all-releases/releases returns any result but other repos e.g. https://api.github.com/repos/stevemao/conventional-github-releaser/releases returns release info. I am not sure what difference is between these repo's release data.

**Comment by stevemao** [comment]
What's in your image is just tags not releases

**Comment by fusionstrings** [comment]
ohh, I ran `conventional-github-releaser` and since I didn't see any change "no changelog" I thought may be I need to run `github-remove-all-releases` first. You are right, just figured it out that anything shown under releases doesn't mean release. Since it shows release count under release tab, I misunderstood.

So basically may be it's `conventional-github-releaser` not generating releases. I tried gulp task as well cli `conventional-github-releaser -p angular -r 0`, no error but no result. Shall I file issue there?
I am extremely sorry about my lack of knowledge and trouble caused to you. 

Please feel free to ignore this comment as it's kind of stretching conversation under closed issue.

**Comment by stevemao** [comment]
No problem ;)

**Comment by stevemao** [comment]
I would prefer if you could send PRs with failure tests so it's easier for me to know the problem.

**Comment by fusionstrings** [comment]
sure

**Comment by fusionstrings** [comment]
Just to conclude this issue, I had repository entry in my package.json as full URL whereas it should be only `username/repository` while running `conventional-github-releaser`. I'll submit PR for documentation.

Once again I can't thank you enough for your wonderful OSS.

**Comment by stevemao** [comment]
No worries. Make sure you cwd is the same as your package.json (this will be improved soon) and try to provide all the options (instead of let it auto config by your package.json) and see if it works.
